branches:
    only:
        - dev

language: python
python:
    - "3.7"
    #- "3.8"

os:
    - linux

dist: xenial

services: xvfb

addons:
    apt:
        packages:
            - x11-utils
            - libxkbcommon-x11-0

install:
    - pip install -U pip
    - pip install -U pytest
    - pip install -U pytest-qt
    - pip install PySide2==5.13.2
    - pip install numpy==1.18.1
    - pip install scipy==1.4.1
    - pip install pandas==0.25.3
    - pip install matplotlib==3.2.1

script:
    - pip install -e .
    - pytest -v