branches:
    only:
        - dev

language: python
python:
    - "3.7"
    - "3.8"

os:
    - linux

install:
    - pip install PySide2==5.13.2
    - pip install numpy==1.18.1
    - pip install scipy==1.4.1
    - pip install pandas==0.25.3
    - pip install matplotlib==3.2.1

script:
    - python pip -e .
    - pytest

