name: pyinstaller
on:
  workflow_dispatch
  # release:
  #   types: [published]

defaults:
  run:
    working-directory: pyinstaller

jobs:

  build_windows:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: pyinstaller_env
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false

    - name: build with pyinstaller
      shell: powershell
      run: | # make sure to add root (..) to paths, otherwise biopeaks cannot be imported
        pyinstaller --onefile --name=biopeaks --icon=python_icon.ico --paths=.. pyinstaller_entry.py
    - name: upload exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: biopeaks_windows
        path: dist/biopeaks.exe