name: test
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:

  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:    # all steps of this job will run using this matrix (matrix not accessible to other jobs)
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        activate-environment: ci_env
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Local install
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Lint
      if: matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: |
        flake8 biopeaks --exclude biopeaks/images,biopeaks/tests/testdata,biopeaks/resources.py --max-complexity=10 --ignore E303,C901,E203,W503,E501,W504,E129,W605,E371,E731

    - name: Test on Windows and MacOS
      if: matrix.os == 'windows-latest' || matrix.os == 'macos-latest'
      shell: bash -l {0}
      run: |
        pytest -v

    - name: Test on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: |    # run coverage only on Ubuntu
        sudo apt-get install -y xvfb x11-utils libxkbcommon-x11-0
        xvfb-run pytest -v --cov-config=.coveragerc --cov-report=xml --cov=biopeaks

    - name: Upload coverage report
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
